### 토큰 재발급 요청
POST http://localhost:8080/api/v1/auth/refresh-access-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYwMDc0MzYsImV4cCI6MTcwNjI2NjYzNn0.7Cnv74WOMVBEKR6K33-EtTyB84DNMuA_FpD1OnduO399LA_tVhCK34V80z1f2dOS9U-CM9D3OqPGLYOmUWKjFQ"
}

### 로그인 사용자 정보 가져오기
GET http://localhost:8080/api/v1/auth/me
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwiaWF0IjoxNzA3MTYwMzUxLCJleHAiOjE3MDcxNjIxNTEsImF1dGhvcml0aWVzIjoiUk9MRV9VU0VSIn0.fWphCix58c1JH30HW-E-trpKpJms9mzfioIZMb5g-psJnfC9flPEgGRvZAN7rCPho0WVwAI47vDgBebqBSBpyg

### 로그아웃
POST http://localhost:8080/api/v1/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYyODY5NTgsImV4cCI6MTcwNjU0NjE1OH0.KPq58t2mWtY5xp-Z-AiBUogIqmWCrXwKuPkCeS8bgr4IyGZwyvttcr8-4tzlSjFLPQuHhQDBs3jBQBSsGdvUkw"
}

### 상품 페이지 조회
GET http://localhost:8080/api/v1/items?page=2

### 상품 조회
GET http://localhost:8080/api/v1/items/1

### 어드민 크롤링 기능
POST http://localhost:8080/api/v1/admin/items/crawl?
    url=https://zigzag.kr/catalog/products/131506009

### 카카오 로그인
GET http://localhost:8080/api/v1/auth/login/kakao
Content-Type: application/json

{
  "redirectUri": "http://localhost:5173",
  "code": "w96QVkTdcA-Vm46eot4CyVncALf9MAyUv8nxLftC60k2VLm9JXVw5f3pxeMKKiWPAAABjXqvbDgicpf3YNJZ6g"
}
