spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      port: 6379
      host: localhost

---

spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      port: 6379
      host: 10.0.1.54
