name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create necessary directories
      run: |
        mkdir -p core/core-infra/core-infra-rdb/src/main/resources
        
    - name: Create application-properties.yml
      run: echo "${{ secrets.APPLICATION_INFRA_RDB }}" > core/core-infra/core-infra-rdb/src/main/resources/application-infra-rdb.yml
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
        
    - name: Build the Docker image
      run: docker build -t ${{secrets.DOCKERHUB_REPOSITORY}}/daldal-api:latest -f ./api/DockerFile .
      
    - name: Docker Push
      run: docker push ${{secrets.DOCKERHUB_REPOSITORY}}/daldal-api:latest
      

  cd:
    needs: ci
    runs-on: ubuntu-latest

    steps:

      - name: Trigger Portainer Webhook
        run: |
          PORTAINER_WEBHOOK_URL="https://portainer:9443/api/webhooks/638e6967-ef77-4906-8af8-236800621360"
          curl -X POST -d "{}" -H "Content-Type: application/json" --insecure $PORTAINER_WEBHOOK_URL
    
